export const menuGallery = [
  {
    id: 1,
    src: "/images/livre/livre-pb-6.jpg",
    width: 1599,
    height: 2400,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, usando top preto e jeans, posando de forma casual e moderna em preto e branco.",
  },
  {
    id: 2,
    src: "/images/livre/livre-pb-1.jpg",
    width: 1601,
    height: 2401,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, olhar suave e cabelo liso escuro, em uma foto em preto e branco, transmitindo elegância e beleza natural.",
  },

  {
    id: 3,
    src: "/images/livre/livre-pb-3.jpg",
    width: 1601,
    height: 2401,
    alt: "Foto de uma mulher jovem com pele clara e cabelos longos, posando elegantemente com as mãos no pescoço, usando roupa preta contra fundo neutro, em preto e branco.",
  },

  {
    id: 4,
    src: "/images/livre/livre-pb-4.jpg",
    width: 1599,
    height: 2400,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, vestindo uma blusa preta e calça larga, sentada de forma casual contra uma parede clara, em preto e branco.",
  },
  {
    id: 5,
    src: "/images/livre/livre-pb-2.jpg",
    width: 1599,
    height: 2400,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, fazendo uma pose artística na foto em preto e branco.",
  },
  {
    id: 6,
    src: "/images/livre/livre-pb-5.jpg",
    width: 1599,
    height: 2400,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, sentada em uma posição casual, vestindo uma blusa preta e calças estilo jeans, em uma foto em preto e branco.",
  },
];

export const projectsGallery = [
  {
    id: 1,
    bg: {
      url: "/images/projetos/projeto-1-1.jpg",
    },
    thumb: "/images/projetos/projeto-1-2.jpg",
    width: 2401,
    height: 3601,
    alt: "Foto de um homem sentado em loja de roupas com camiseta verde e preta e tênis branco, usando fones de ouvido, ao lado de roupas coloridas na parede.",
  },
  {
    id: 2,
    bg: {
      url: "/images/projetos/projeto-2-1.jpg",
    },
    thumb: "/images/projetos/projeto-2-2.jpg",
    width: 2401,
    height: 3001,
    alt: "Foto de uma mulher com cabelo curto e escuro segurando um buquê de flores coloridas, com expressão confiante, usando blazer bege e fundo vermelho.",
  },
];

export const categoriesGallery = [
  {
    id: 1,
    category: "moda",
    src: "/images/moda/moda-1.jpg",
    width: 2401,
    height: 3001,
    alt: "Foto de uma mulher estilosa com blazer vermelho, chapéu bege e bolsa de mão, posando ao ar livre em ambiente urbano na cidade de dia.",
  },
  {
    id: 2,
    category: "moda",
    src: "/images/moda/moda-2.jpg",
    width: 2401,
    height: 3001,
    alt: "Foto de uma mulher estilosa com blazer vermelho, usando chapéu bege e calças de estampa xadrez, posando ao ar livre em ambiente urbano de dia.",
  },
  {
    id: 3,
    category: "moda",
    src: "/images/moda/moda-3.jpg",
    width: 2401,
    height: 3001,
    alt: "Foto de uma mulher estilosa com casaco vermelho, chapéu bege e calça de xadrez, posando de forma criativa sob estrutura de concreto moderna.",
  },
  {
    id: 4,
    category: "moda",
    src: "/images/moda/moda-4.jpg",
    width: 2400,
    height: 3000,
    alt: "Foto de uma mulher usando casaco vermelho, calça xadrez e chapéu bege posando ao lado de paredes de concreto com arcos em cenário urbano moderno.",
  },
  {
    id: 5,
    category: "moda",
    src: "/images/moda/moda-5.jpg",
    width: 2401,
    height: 3001,
    alt: "Foto de uma mulher usando casaco vermelho, chapéu bege e calça xadrez posando em escadaria de concreto em cenário urbano",
  },
  {
    id: 6,
    category: "moda",
    src: "/images/moda/moda-6.jpg",
    width: 2400,
    height: 3000,
    alt: "Foto de uma mulher com estilo fashion usando blazer vermelho longo, calça xadrez, bota preta e chapéu bege em ambiente urbano com estrutura de concreto",
  },
  {
    id: 7,
    category: "casamento",
    src: "/images/casamento/casamento-1.jpg",
    width: 2402,
    height: 3597,
    alt: "Foto de uma noiva com vestido branco elegante segurando um buquê de flores em um campo ao ar livre.",
  },
  {
    id: 8,
    category: "casamento",
    src: "/images/casamento/casamento-2.jpg",
    width: 1668,
    height: 2500,
    alt: "Foto de brincos de pérola com detalhes de ouro e diamantes, destaque para uma mulher segurando as joias em uma mão, com fundo levemente desfocado.",
  },
  {
    id: 9,
    category: "casamento",
    src: "/images/casamento/casamento-3.jpg",
    width: 1668,
    height: 2500,
    alt: "Foto de um convite de casamento, buquê de flores com rosas, sapatos brancos de salto alto e envelope rosa sobre piso de madeira.",
  },
  {
    id: 10,
    category: "casamento",
    src: "/images/casamento/casamento-4.jpg",
    width: 2401,
    height: 1602,
    alt: "Foto de um homem servindo champanhe em taças em uma festa ao ar livre, com uma mesa de doces ao fundo.",
  },
  {
    id: 11,
    category: "casamento",
    src: "/images/casamento/casamento-5.jpg",
    width: 2336,
    height: 3500,
    alt: "Foto de um vestido de noiva branco delicado e salto alto cor de rosa, pendurados na porta de um closet, pronto para o casamento.",
  },
  {
    id: 12,
    category: "casamento",
    src: "/images/casamento/casamento-6.jpg",
    width: 2402,
    height: 3596,
    alt: "Foto de uma noiva segurando um buquê de flores em um cenário ao ar livre, com vestido de noiva branco e céu azul ao fundo, um casamento ao ar livre.",
  },
  {
    id: 13,
    category: "corporativo",
    src: "/images/corporativo/corporativo-1.jpg",
    width: 2400,
    height: 3600,
    alt: "Foto de um homem de óculos escuros e suéter rosa em ambiente de escritório moderno.",
  },
  {
    id: 14,
    category: "corporativo",
    src: "/images/corporativo/corporativo-2.jpg",
    width: 2400,
    height: 3600,
    alt: "Foto de uma mulher de cabelo loiro e expressão séria, usando blazer cinza claro, segurando óculos e uma folha de papel, posicionada numa sala moderna.",
  },
  {
    id: 15,
    category: "corporativo",
    src: "/images/corporativo/corporativo-3.jpg",
    width: 2400,
    height: 1601,
    alt: "Foto de uma reunião de negócios com diversidade cultural, com uma pessoa apresentando em frente ao grupo em uma sala moderna com vista urbana.",
  },
  {
    id: 16,
    category: "corporativo",
    src: "/images/corporativo/corporativo-4.jpg",
    width: 2400,
    height: 1601,
    alt: "Foto de um homem de negócios usando telefone celular em ambiente corporativo moderno, com expressão séria e atento às informações recebidas.",
  },
  {
    id: 17,
    category: "corporativo",
    src: "/images/corporativo/corporativo-5.jpg",
    width: 2400,
    height: 3600,
    alt: "Foto de um homem de camiseta de gola alta azul escuro, óculos e barba, sorrindo e posando com os braços cruzados em um ambiente de escritório.",
  },
  {
    id: 18,
    category: "corporativo",
    src: "/images/corporativo/corporativo-6.jpg",
    width: 2400,
    height: 3600,
    alt: "Foto de dois homens discutindo em frente a um computador em um escritório moderno, enquanto outros colegas trabalham ao fundo em um ambiente corporativo.",
  },
  {
    id: 19,
    category: "livre",
    src: "/images/livre/livre-1.jpg",
    width: 2401,
    height: 3601,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, fazendo uma pose artística na foto.",
  },
  {
    id: 20,
    category: "livre",
    src: "/images/livre/livre-2.jpg",
    width: 2401,
    height: 3600,
    alt: "Foto de uma mulher jovem com pele clara e cabelos longos, posando elegantemente com as mãos no pescoço e usando roupa preta contra fundo neutro.",
  },
  {
    id: 21,
    category: "livre",
    src: "/images/livre/livre-3.jpg",
    width: 2401,
    height: 3600,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, olhar suave e cabelo liso escuro, transmitindo elegância e beleza natural.",
  },
  {
    id: 22,
    category: "livre",
    src: "/images/livre/livre-4.jpg",
    width: 2401,
    height: 3601,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, vestindo uma blusa preta e calça larga e sentada de forma casual contra uma parede clara.",
  },
  {
    id: 23,
    category: "livre",
    src: "/images/livre/livre-5.jpg",
    width: 2401,
    height: 3601,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, sentada em uma posição casual e vestindo uma blusa preta e calças estilo jeans.",
  },
  {
    id: 24,
    category: "livre",
    src: "/images/livre/livre-6.jpg",
    width: 2401,
    height: 3601,
    alt: "Foto de uma jovem mulher com pele clara e cabelos longos, usando top preto e jeans, posando de forma casual e moderna.",
  },
];
